repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: detect-private-key
      - id: check-added-large-files
        args:
          - "--maxkb=100"
      - id: check-yaml
      # - id: check-json
      # - id: pretty-format-json
      #   args:
      #     - "--no-sort-keys"
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black

default_stages:
  - pre-commit
  - pre-push
