services:
  lent-app:
    env_file:
      - .env.dev
    volumes:
      - ./data:/data
      # - ./static:/static
      # - ./src:/src
    # stdin_open: true
    develop:
      watch:
        - action: sync
          path: ./src
          target: /src
