# Generated by Django 5.0.2 on 2024-02-11 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lentapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itemlend",
            old_name="date_end",
            new_name="time_end",
        ),
        migrations.RenameField(
            model_name="itemlend",
            old_name="date_lend",
            new_name="time_lend",
        ),
        migrations.RenameField(
            model_name="itemlend",
            old_name="date_return",
            new_name="time_return",
        ),
        migrations.RenameField(
            model_name="itemlend",
            old_name="date_start",
            new_name="time_start",
        ),
        migrations.RemoveField(
            model_name="lenditem",
            name="currently_lent",
        ),
    ]
