# Generated by Django 5.0.2 on 2024-02-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lentapp", "0002_rename_date_end_itemlend_time_end_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemowner",
            name="name",
        ),
    ]
