# Generated by Django 5.0.2 on 2024-02-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lentapp", "0003_remove_itemowner_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemlend",
            name="time_end",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="itemlend",
            name="time_lend",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="itemlend",
            name="time_return",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="itemlend",
            name="time_start",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="lenditem",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="lenditem",
            name="readiness_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="lenditem",
            name="use_conditions",
            field=models.TextField(blank=True),
        ),
    ]
