# Generated by Django 5.0.2 on 2024-02-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lentapp", "0004_alter_itemlend_time_end_alter_itemlend_time_lend_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemowner",
            name="contact_details",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
